### ISSUE TITLE
problem with software-tab

### ISSUE THREAD

**Issue by drazioti** [CSD-FOSS-Team/genume#74]
![screenshot from 2019-02-23 20 39 57](https://user-images.githubusercontent.com/7658241/53290354-5b2b2400-37ab-11e9-87e3-da98d721640e.png)
@xlxs4

**Comment by xlxs4** [comment]
Running the command on your system and posting the traceback call would help. An app or two are bound to error out on the output since I didnt have them all installed, neither could I find man documentation for all of them, thus some do not have a `--version` command, but a similar variation.

The list will be polished will the help of the genume testers to fill in the blanks. I'll try check kiki on my own, but I can only find it in an obsolete git repo and in a non compatible old AUR package.
